### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by hafizahmmed** [rstockbridge/Photos#1]
Hello,
Good Day, i make a logo icon for your project. If you want to use this logo in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.It's totally free for open source project.

![cameramanager-01](https://user-images.githubusercontent.com/38810169/42290355-946d0d96-7fe6-11e8-9099-d6a5437c79e0.jpg)

**Comment by rstockbridge** [comment]
This is just a tiny little practice app, so I don't need a logo, but I appreciate the suggestion!
